security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        database_users:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            form_login:
                login_path: app_login
                check_path: app_login
                username_parameter: username
                password_parameter: password
            logout:
                path: app_logout

    access_control:
        - { path: ^/products/create, roles: ROLE_ADMIN }
        - { path: ^/products/\d+/edit, roles: ROLE_ADMIN }
        - { path: ^/products/\d+/delete, roles: ROLE_ADMIN }